# Site settings
title: Sagor | Enthusiastic AI Learner
description: "An Enthusiastic AI Learner"
url: "https://sagorbrur.github.io/"
author:
  name: "Sagor Sarker"
  email: "brursagor@gmail.com"
  url: "https://sagorbrur.github.io/"

# Build settings
baseurl: /blog/ # Change this to your relative path (ex: /blog/), or leave just a / Default: emerald/
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
